#!/usr/bin/env python3

##04_Default_HOSTS


import getpass
import telnetlib

user = input("Enter your remote account: ")
password = getpass.getpass()
f1 = open("Routers.txt")
f2 = open("Switches.txt")


for file in (f1, f2):
    for line in file:
        tn = telnetlib.Telnet(line)
        tn.read_until(b"Username: ")
        tn.write(user.encode('ascii') + b"\n")

        if password:
            tn.read_until(b"Password: ")
            tn.write(password.encode('ascii') + b"\n")

        tn.write(b"conf t\n")
##### Configure HOSTS
        tn.write(b"ip host pc1 10.0.1.2\n")
        tn.write(b"ip host pc2 10.0.2.2\n")
        tn.write(b"ip host pc3 10.0.3.2\n")
        tn.write(b"ip host pc4 10.0.4.2\n")
        tn.write(b"ip host ub1 10.0.0.2\n")

        tn.write(b"ip host sw1 10.0.0.4\n")
        tn.write(b"ip host sw2 10.0.0.5\n")
        tn.write(b"ip host sw3 10.0.0.6\n")
        tn.write(b"ip host sw4 10.0.0.10\n")
        tn.write(b"ip host sw5 10.0.0.9\n")

        tn.write(b"ip host r1 10.0.0.3\n")
        tn.write(b"ip host r2 10.0.0.7\n")
        tn.write(b"ip host r3 10.0.0.8\n")
        tn.write(b"ip host r4 10.0.0.11\n")
        tn.write(b"ip host ispe 10.0.0.1\n")
##### EXIT, WRITE MEMORY, and LOGOUT
        tn.write(b"exit\n")
        tn.write(b"exit\n")
        tn.write(b"cop r s\n")
        tn.write(b"\n")
        tn.write(b"exit\n")
        print("\n*** START ***")
        print("****"+ line + "\n")
        print(tn.read_all().decode('ascii'))
        print("*** COMPLETE ***")
        print("****"+ line + "\n")
