#!/usr/bin/env python3

##04_Default_HOSTS


import getpass
import telnetlib

user = input("Enter your remote account: ")
password = getpass.getpass()
Routers = open("Routers.txt")
Switches = open("Switches.txt")


for file in (Routers, Switches):
    print(file.name)
    for line in file:
        HOST = line.strip()
        tn = telnetlib.Telnet(HOST)
        tn.read_until(b"Username: ")
        tn.write(user.encode('ascii') + b"\n")

        if password:
            tn.read_until(b"Password: ")
            tn.write(password.encode('ascii') + b"\n")
        tn.write(b"terminal length 0\n")
        tn.write(b"show running-config | i hostname\n")
#        HOSTNAME = tn.read_all().decode('ascii')
#        print("Getting Running Config From: " + str(HOSTNAME) + str(HOST))
        print("Getting Running Config From: " + str(HOST))
        tn.write(b"show running-config\n")
        tn.write(b"exit\n")

        readOUTPUT = tn.read_all().decode('ascii')

        if file == Routers:
            saveOUTPUT = open("Router_" + HOST, 'w')
        if file == Switches:
            saveOUTPUT = open("Switch_" + HOST, 'w')

        saveOUTPUT.write(str(readOUTPUT))
        saveOUTPUT.close

##### EXIT, WRITE MEMORY, and LOGOUT
        tn.write(b"exit\n")
        tn.write(b"exit\n")
        tn.write(b"cop r s\n")
        tn.write(b"\n")
        tn.write(b"exit\n")
        print("\n*** START ***")
        print("****"+ line + "\n")
        print(tn.read_all().decode('ascii'))
        print("*** COMPLETE ***")
        print("****"+ line + "\n")
